export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_SUCCESS_USER = 'CREATE_SUCCESS_USER';
export const CREATE_ERROR_USER = 'CREATE_ERROR_USER';

export const CREATE_CUSTOMER_TICKET = 'CREATE_CUSTOMER_TICKET';
export const CREATE_CUSTOMER_TICKET_SUCCESS = 'CREATE_CUSTOMER_TICKET_SUCCESS';
export const CREATE_CUSTOMER_TICKET_ERROR = 'CREATE_CUSTOMER_TICKET_ERROR';

export const CUSTOMER_TICKET_LIST = 'CUSTOMER_TICKET_LIST';
export const CUSTOMER_TICKET_LIST_SUCCESS = 'CUSTOMER_TICKET_LIST_SUCCESS';
export const CUSTOMER_TICKET_LIST_ERROR = 'CUSTOMER_TICKET_LIST_ERROR';

export const AGENT_TICKET_LIST = 'AGENT_TICKET_LIST';
export const AGENT_TICKET_LIST_SUCCESS = 'AGENT_TICKET_LIST_SUCCESS';
export const AGENT_TICKET_LIST_ERROR = 'AGENT_TICKET_LIST_ERROR';
export const UPDATE_AGENT_TICKET_LIST = 'UPDATE_AGENT_TICKET_LIST';

export const UPDATE_TICKET_STATUS = 'UPDATE_TICKET_STATUS';
export const UPDATE_TICKET_STATUS_SUCCESS = 'UPDATE_TICKET_STATUS_SUCCESS';
export const UPDATE_TICKET_STATUS_ERROR = 'UPDATE_TICKET_STATUS_ERROR';



export const REHYDRATED_DONE = 'REHYDRATED_DONE';
